[package]
name = "gooful"
version = "0.1.0"
authors = ["up9cloud <8325632+up9cloud@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "main"
path = "server/main.rs"
