on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - id: fleek
        uses: itera-network/action-deploy@master
        with:
          apiKey: ${{ secrets.FLEEK_API_KEY }}
      - uses: itera-network/actions-coudflare-dns@master
        with:
          name: ${{ github.event.repository.name }}
          cid: ${{ steps.fleek.outputs.siteCid }}
          gateway: ${{ secrets.IPFS_GATEWAY }}
          token: ${{ secrets.CF_API_TOKEN }}
          zone: ${{ secrets.CF_ZONE_ID }}
      - uses: up9cloud/action-notify@master
        if: cancelled() == false
        env:
          GITHUB_JOB_STATUS: ${{ job.status }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_CHAT_ID}}
